/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright (c) 2023 Amol Surati */

#ifndef PUB_ERROR_H
#define PUB_ERROR_H

enum {
	ERR_SUCCESS,
	ERR_NO_MATCH,
	ERR_BAD_FILE,
	ERR_UNSUPPORTED,
	ERR_INVALID_PARAMETER,
	ERR_NOT_FOUND,
	ERR_NO_MEMORY,
	ERR_OPEN_FILE,
	ERR_END_OF_FILE,
	ERR_UNEXPECTED_END_OF_FILE,
	ERR_INVALID_CODE_POINT,
	ERR_INVALID_TOKEN,
};
#endif
